"""Workflow graphs, run and node state, log entries."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

MAX_RETRIES = 3
"""Orchestrator retry limit (M2 §6.3). Mirrored by the `retry_count <= 3` check in the database."""


class NodeStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    RETRYING = "retrying"
    AWAITING_APPROVAL = "awaiting_approval"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"


TERMINAL_NODE_STATUSES = frozenset({NodeStatus.SUCCESS, NodeStatus.FAILED, NodeStatus.SKIPPED})


class RunStatus(StrEnum):
    QUEUED = "queued"
    RUNNING = "running"
    AWAITING_APPROVAL = "awaiting_approval"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"


TERMINAL_RUN_STATUSES = frozenset({RunStatus.SUCCEEDED, RunStatus.FAILED, RunStatus.CANCELLED})


class ApprovalDecision(StrEnum):
    APPROVE = "approve"
    REJECT = "reject"


class OutputType(StrEnum):
    TEXT = "text"
    FILE = "file"
    URL = "url"


class Position(BaseModel):
    x: float = 0
    y: float = 0


class GraphNode(BaseModel):
    """One agent on the canvas. `id` is generated by the frontend (crypto.randomUUID())."""

    model_config = ConfigDict(extra="forbid")

    id: UUID
    agent_type: str = Field(min_length=1, max_length=64, pattern=r"^[a-z][a-z0-9_]*$")
    configuration: dict[str, Any] = Field(default_factory=dict)
    requires_approval: bool = False
    position: Position = Field(default_factory=Position)


class GraphEdge(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=128)
    source: UUID
    target: UUID


class WorkflowGraph(BaseModel):
    """What the canvas saves into `workflows.graph_definition`. Never holds secrets."""

    model_config = ConfigDict(extra="forbid")

    nodes: list[GraphNode] = Field(default_factory=list)
    edges: list[GraphEdge] = Field(default_factory=list)


class NodeState(BaseModel):
    node_id: UUID
    agent_type: str
    status: NodeStatus
    retry_count: int = Field(0, ge=0, le=MAX_RETRIES)
    started_at: datetime | None = None
    completed_at: datetime | None = None
    duration_ms: int | None = None
    error_message: str | None = None


class LogEntry(NodeState):
    id: UUID
    run_id: UUID


class RunState(BaseModel):
    id: UUID
    workflow_id: UUID
    status: RunStatus
    created_at: datetime | None = None
    started_at: datetime | None = None
    completed_at: datetime | None = None
    total_nodes: int = 0
    failed_nodes: int = 0
    nodes: list[NodeState] = Field(default_factory=list)
