import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, within } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { ToastProvider } from "@/design-system/components/Toast";
import { OutputsPage } from "./OutputsPage";
import { endpoints, type AgentManifest, type OutputLink, type RunOutput, type RunState } from "@/lib/api";
import catalog from "@/test/catalog.json";

// P-09 / S-08. The page's job is that a person can get at what the run made, so these cover the
// three shapes it groups into, the download, and the states where there is nothing to give.

const agents = catalog as unknown as AgentManifest[];
const RUN = "00000000-0000-4000-8000-0000000000cc";

const run = (over: Partial<RunState> = {}): RunState => ({
  id: RUN,
  workflow_id: "wf-1",
  status: "succeeded",
  created_at: "2026-09-20T10:00:00Z",
  started_at: "2026-09-20T10:00:00Z",
  completed_at: "2026-09-20T10:06:12Z",
  total_nodes: 4,
  failed_nodes: 0,
  nodes: [],
  ...over,
});

const output = (over: Partial<RunOutput>): RunOutput => ({
  id: "o1",
  node_id: "n1",
  agent_type: "video",
  kind: "file",
  filename: null,
  mime_type: null,
  bytes: null,
  created_at: "2026-09-20T10:00:00Z",
  ...over,
});

function show(outputs: RunOutput[], links: Record<string, OutputLink> = {}, state: RunState = run()) {
  vi.spyOn(endpoints, "runState").mockResolvedValue(state);
  vi.spyOn(endpoints, "runOutputs").mockResolvedValue(outputs);
  vi.spyOn(endpoints, "catalog").mockResolvedValue(agents);
  vi.spyOn(endpoints, "output").mockImplementation(async (id: string) => links[id] ?? { id, url: null, expires_in: 0, text: null });
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <QueryClientProvider client={client}>
      <ToastProvider>
        <MemoryRouter initialEntries={[`/runs/${RUN}/outputs`]}>
          <Routes>
            <Route path="/runs/:runId/outputs" element={<OutputsPage />} />
          </Routes>
        </MemoryRouter>
      </ToastProvider>
    </QueryClientProvider>,
  );
}

afterEach(() => vi.restoreAllMocks());

describe("OutputsPage", () => {
  it("gives a file its name, type, size and a download that points at the file", async () => {
    show(
      [output({ id: "v", filename: "video.mp4", mime_type: "video/mp4", bytes: 4036 })],
      { v: { id: "v", url: "https://files.test/video.mp4", expires_in: 3600 } },
    );

    expect(await screen.findByText("video.mp4")).toBeInTheDocument();
    expect(screen.getByText("MP4")).toBeInTheDocument();
    expect(screen.getByText(/4\.0 KB/)).toBeInTheDocument();
    // Whose it is comes from the catalog, never from the agent's raw type.
    expect(screen.getByText(/Generated by/)).toHaveTextContent("Video");

    const download = await screen.findByRole("link", { name: /Download/ });
    expect(download).toHaveAttribute("href", "https://files.test/video.mp4");
    expect(download).toHaveAttribute("download", "video.mp4");
    // Files come from another origin, so `download` is ignored — without this the click would
    // navigate the app away and play the video where the app used to be.
    expect(download).toHaveAttribute("target", "_blank");
  });

  it("separates what was published from what was made", async () => {
    show(
      [
        output({ id: "u", agent_type: "publisher", kind: "url" }),
        output({ id: "f", filename: "a.pdf", mime_type: "application/pdf", bytes: 180_000 }),
      ],
      {
        u: { id: "u", url: "https://youtu.be/abc123", expires_in: 0 },
        f: { id: "f", url: "https://files.test/a.pdf", expires_in: 3600 },
      },
    );

    const publishedSection = await screen.findByRole("region", { name: "Published" });
    expect(await within(publishedSection).findByText("https://youtu.be/abc123")).toBeInTheDocument();
    expect(within(publishedSection).getByRole("link", { name: /Open/ })).toHaveAttribute("href", "https://youtu.be/abc123");

    const files = screen.getByRole("region", { name: "Files" });
    expect(within(files).getByText("a.pdf")).toBeInTheDocument();
    expect(within(files).getByText("PDF")).toBeInTheDocument();
    expect(within(files).getByText(/180 KB/)).toBeInTheDocument();
    // Grouping has to exclude as well as include: a link listed in both sections would otherwise pass.
    expect(within(files).queryByText("https://youtu.be/abc123")).not.toBeInTheDocument();
    expect(within(publishedSection).queryByText("a.pdf")).not.toBeInTheDocument();
    expect(within(files).getByRole("heading", { name: "1 file", level: 2 })).toBeInTheDocument();
  });

  it("shows the words a run produced, with a way to take them", async () => {
    show([output({ id: "t", agent_type: "writer", kind: "text" })], {
      t: { id: "t", url: null, expires_in: 0, text: "article:\n# The Future of Solar Energy" },
    });
    const text = await screen.findByRole("region", { name: "Text" });
    expect(within(text).getByRole("heading", { name: "Writer", level: 3 })).toBeInTheDocument();
    expect(await within(text).findByText(/The Future of Solar Energy/)).toBeInTheDocument();
    expect(within(text).getByRole("button", { name: /Copy text/ })).toBeInTheDocument();
  });

  it("tells a run still going that files are coming", async () => {
    show([], {}, run({ status: "running", completed_at: null }));
    expect(await screen.findByText(/each one shows up as soon as its step finishes/)).toBeInTheDocument();
  });

  it("tells a failed run that nothing was made", async () => {
    show([], {}, run({ status: "failed" }));
    expect(await screen.findByText(/The run stopped before anything was produced/)).toBeInTheDocument();
  });

  it("does not tell someone who stopped a run that it failed", async () => {
    // The worker records a rejection as `failed`; §2 rule 7 says it never reads as one.
    show([], {}, run({
      status: "failed",
      nodes: [{ node_id: "n", agent_type: "publisher", status: "failed", retry_count: 0, started_at: null, completed_at: null, duration_ms: null, error_message: "[attempt 1] Rejected by reviewer." }],
    }));
    expect(await screen.findByText("Rejected by you")).toBeInTheDocument();
    expect(screen.getByText(/You stopped this run/)).toBeInTheDocument();
    expect(screen.queryByText("Failed")).not.toBeInTheDocument();
  });

  it("says a cancelled run simply made nothing", async () => {
    show([], {}, run({ status: "cancelled" }));
    expect(await screen.findByText(/didn't produce any files/)).toBeInTheDocument();
  });

  it("leaves a download that has no URL out of the tab order", async () => {
    // pointer-events-none stops a mouse but not a keyboard; an anchor with no href is not focusable.
    show([output({ id: "f", filename: "a.pdf", mime_type: "application/pdf" })], {});
    const download = await screen.findByText(/Download/);
    const anchor = download.closest("a")!;
    expect(anchor).not.toHaveAttribute("href");
    expect(anchor).toHaveAttribute("aria-disabled", "true");
  });

  it("offers to run it again only once the run is over", async () => {
    show([], {}, run({ status: "running", completed_at: null }));
    expect(await screen.findByText("Nothing here yet")).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Run this workflow again" })).not.toBeInTheDocument();
  });

  it("offers to run it again when it is", async () => {
    show([]);
    expect(await screen.findByRole("button", { name: "Run this workflow again" })).toBeInTheDocument();
  });
});
