import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, ExternalLink } from "lucide-react";
import { useParams } from "react-router-dom";
import { AppShell, PageBody } from "@/components/app/AppShell";
import { Button } from "@/design-system/components/Button";
import { Card } from "@/design-system/components/Card";
import { EmptyState } from "@/design-system/components/EmptyState";
import { StatusChip } from "@/design-system/status/StatusChip";
import { nodeStatusMeta, runStatusMeta, TERMINAL_RUN_STATUSES } from "@/design-system/status/statusMeta";
import { API_URL, endpoints, type RunOutput } from "@/lib/api";

function fileUrl(path: string) {
  const safePath = path.split("/").map(encodeURIComponent).join("/");
  return `${API_URL}/files/${safePath}`;
}

async function downloadFile(url: string, filename: string) {
  const response = await fetch(url);
  if (!response.ok) throw new Error("Couldn't download this image.");
  const objectUrl = URL.createObjectURL(await response.blob());
  const link = document.createElement("a");
  link.href = objectUrl;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(objectUrl);
}

function imagePaths(output: RunOutput) {
  const paths = output.content_json?.image_paths;
  if (Array.isArray(paths)) return paths.filter((path): path is string => typeof path === "string");
  return output.storage_path && output.mime_type?.startsWith("image/") ? [output.storage_path] : [];
}

function videoPaths(output: RunOutput) {
  const path = output.content_json?.video_path;
  if (typeof path === "string") return [path];
  return output.storage_path && (output.mime_type?.startsWith("video/") || output.storage_path.endsWith(".mp4"))
    ? [output.storage_path]
    : [];
}

function ImageOutput({ paths }: { paths: string[] }) {
  return (
    <div className="grid gap-4 sm:grid-cols-2">
      {paths.map((path) => {
        const url = fileUrl(path);
        const filename = path.split("/").at(-1) ?? "image";
        return (
          <figure key={path} className="grid gap-3 overflow-hidden rounded-md border border-border bg-surface-raised p-3">
            <a href={url} target="_blank" rel="noreferrer" className="block overflow-hidden rounded-sm bg-surface-hover">
              <img src={url} alt="Generated by the Image agent" className="aspect-video w-full object-cover" />
            </a>
            <figcaption className="flex flex-wrap gap-2">
              <a href={url} target="_blank" rel="noreferrer" className="inline-flex h-7 items-center gap-1.5 rounded-sm bg-surface px-2.5 text-caption text-text ring-1 ring-border-strong hover:bg-surface-hover">
                <ExternalLink size={14} aria-hidden /> Open image
              </a>
              <Button size="sm" icon={<Download size={14} aria-hidden />} onClick={() => void downloadFile(url, filename)}>
                Download
              </Button>
            </figcaption>
          </figure>
        );
      })}
    </div>
  );
}

function VideoOutput({ paths }: { paths: string[] }) {
  return (
    <div className="grid gap-4">
      {paths.map((path) => {
        const url = fileUrl(path);
        const filename = path.split("/").at(-1) ?? "video.mp4";
        return (
          <figure key={path} className="grid gap-3 overflow-hidden rounded-md border border-border bg-surface-raised p-3">
            <video controls preload="metadata" className="aspect-video w-full rounded-sm bg-surface-inverse" src={url}>
              Your browser can’t play this video. Use the download button instead.
            </video>
            <figcaption className="flex flex-wrap gap-2">
              <a href={url} target="_blank" rel="noreferrer" className="inline-flex h-7 items-center gap-1.5 rounded-sm bg-surface px-2.5 text-caption text-text ring-1 ring-border-strong hover:bg-surface-hover">
                <ExternalLink size={14} aria-hidden /> Open video
              </a>
              <Button size="sm" icon={<Download size={14} aria-hidden />} onClick={() => void downloadFile(url, filename)}>
                Download
              </Button>
            </figcaption>
          </figure>
        );
      })}
    </div>
  );
}

function OutputContent({ output }: { output: RunOutput }) {
  const values = output.content_json ?? {};
  const images = imagePaths(output);
  const videos = videoPaths(output);
  const article = typeof values.article_md === "string" ? values.article_md : null;
  if (videos.length) return <VideoOutput paths={videos} />;
  if (images.length) return <ImageOutput paths={images} />;
  if (article) return <pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap text-body-md text-text">{article}</pre>;
  if (output.content) return <pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap text-body-md text-text">{output.content}</pre>;
  if (output.storage_path) return <p className="text-body-md text-text-muted">File saved at {output.storage_path}</p>;
  return <pre className="max-h-[20rem] overflow-auto whitespace-pre-wrap font-mono text-mono-sm text-text">{JSON.stringify(values, null, 2)}</pre>;
}

// S-05 skeleton (DESIGN-SYSTEM.md §21). Polls every 2 s (GP-plan W3 allows this before Realtime).
// TODO(W3, Ahmed): run header, read-only canvas, retry strip; TODO(W7): approval screen S-06.
export function RunPage() {
  const { runId = "" } = useParams();
  const queryClient = useQueryClient();
  const run = useQuery({
    queryKey: ["run", runId],
    queryFn: () => endpoints.runState(runId),
    refetchInterval: (query) => (query.state.data && TERMINAL_RUN_STATUSES.has(query.state.data.status) ? false : 2000),
  });
  const outputs = useQuery({
    queryKey: ["run-outputs", runId],
    queryFn: () => endpoints.runOutputs(runId),
    enabled: Boolean(runId),
    refetchInterval: () => (run.data && TERMINAL_RUN_STATUSES.has(run.data.status) ? false : 2000),
  });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["run", runId] });
  const approve = useMutation({ mutationFn: (nodeId: string) => endpoints.approve(runId, nodeId, "approve"), onSuccess: refresh });
  const cancel = useMutation({ mutationFn: () => endpoints.cancel(runId), onSuccess: refresh });

  const state = run.data;
  const done = state?.nodes?.filter((n) => n.status === "success").length ?? 0;

  return (
    <AppShell crumbs={[{ label: "Workflows", to: "/workflows" }, { label: `Run ${runId.slice(0, 8)}` }]}>
      <PageBody width="narrow">
        {run.isError && <p role="alert" className="text-status-failed-fg">{run.error.message}</p>}
        {state && (
          <>
            <div className="flex flex-wrap items-center gap-3">
              <h1 className="text-heading-lg">Run</h1>
              <StatusChip meta={runStatusMeta[state.status]} />
              <span className="font-mono text-mono-sm text-text-muted">
                {done} of {state.total_nodes} steps
              </span>
              {!TERMINAL_RUN_STATUSES.has(state.status) && (
                <Button className="ml-auto" onClick={() => cancel.mutate()} loading={cancel.isPending}>
                  Cancel run
                </Button>
              )}
            </div>
            <ol className="grid gap-2" aria-live="polite">
              {state.nodes?.map((node, i) => (
                <li key={node.node_id} className="grid gap-2 rounded-md border border-border bg-surface p-4 shadow-1">
                  <div className="flex flex-wrap items-center gap-3">
                    <span className="font-mono text-mono-sm text-text-muted">{i + 1}</span>
                    <span className="text-body-md font-medium capitalize">{node.agent_type}</span>
                    <StatusChip
                      meta={nodeStatusMeta[node.status]}
                      label={node.status === "retrying" ? `Retrying ${node.retry_count}/3` : undefined}
                    />
                    {node.duration_ms != null && (
                      <span className="ml-auto font-mono text-mono-sm text-text-muted">{(node.duration_ms / 1000).toFixed(1)} s</span>
                    )}
                    {node.status === "awaiting_approval" && (
                      <Button variant="primary" size="sm" className="ml-auto" onClick={() => approve.mutate(node.node_id)} loading={approve.isPending}>
                        Approve
                      </Button>
                    )}
                  </div>
                  {node.error_message && <pre className="whitespace-pre-wrap font-mono text-mono-sm text-status-failed-fg">{node.error_message}</pre>}
                </li>
              ))}
            </ol>
            <section className="grid gap-3" aria-labelledby="outputs-heading">
              <div>
                <h2 id="outputs-heading" className="text-heading-md">Outputs</h2>
                <p className="text-body-md text-text-muted">Results saved by each completed step.</p>
              </div>
              {outputs.isError && <p role="alert" className="text-status-failed-fg">Couldn’t load outputs. Try refreshing the page.</p>}
              {outputs.data?.length === 0 && TERMINAL_RUN_STATUSES.has(state.status) && (
                <Card padding="compact"><EmptyState art={false} title="No outputs were saved" body="This run finished without a readable result." /></Card>
              )}
              {outputs.data?.map((output) => (
                <Card key={output.id} padding="compact" className="grid gap-3">
                  <div className="flex items-center justify-between gap-3">
                    <h3 className="text-body-lg font-medium capitalize">{output.agent_type}</h3>
                    <span className="font-mono text-mono-sm text-text-muted">{output.output_type}</span>
                  </div>
                  <OutputContent output={output} />
                </Card>
              ))}
            </section>
          </>
        )}
      </PageBody>
    </AppShell>
  );
}
