/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog
         * @description Every installed agent with the JSON Schema of its configuration. Drives the palette and the
         *     configuration drawer, so a new agent appears with a working form and no frontend change (NFR-04).
         *     Empty until a worker has started.
         */
        get: operations["catalog_agents_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Login
         * @description Development only: sign in as any email, no password. Disabled when ENVIRONMENT=production.
         *
         *     TODO(W2, Hasan): /auth/register and /auth/login — delegated to Supabase Auth once D-01 is signed off.
         */
        post: operations["dev_login_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Connect
         * @description Return Google's consent URL; the browser navigates there only after the user chooses to connect.
         */
        post: operations["google_connect_auth_google_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Status
         * @description Report connection state without exposing any OAuth token or account data.
         */
        get: operations["google_status_auth_google_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Google
         * @description Begin connecting a Google account. Call with `credentials: "include"` so the browser keeps the
         *     cookie that ties Google's answer to this browser; then open `authorization_url`.
         */
        post: operations["start_google_connections_google_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect
         * @description Forget a connection. Steps that used it then show "needs a Google connection".
         */
        delete: operations["disconnect_connections__credential_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. Cheap, no dependencies.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: database reachable, and whether a worker has published the agent catalog.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outputs/{output_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description Return a download URL — the API never streams files itself.
         *
         *     With STORAGE_BACKEND=supabase the URL is a short-lived signed link into the private bucket;
         *     otherwise (development) files are served from STORAGE_ROOT at /files. Either way only the
         *     output's owner gets a link — anyone else gets 404.
         */
        get: operations["download_outputs__output_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Approvals
         * @description UC-04 audit trail: every decision recorded against this run, oldest first (S-06, report evidence).
         */
        get: operations["run_approvals_runs__run_id__approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_runs__run_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/nodes/{node_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description UC-04: record the decision, then hand the run back to the worker, which resumes or halts it.
         */
        post: operations["decide_runs__run_id__nodes__node_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Outputs
         * @description What this run produced, in the order the steps ran.
         *
         *     The worker already records every output; this exposes them so a person can see, download and
         *     approve the actual article, image and video rather than being told a file exists somewhere.
         */
        get: operations["run_outputs_runs__run_id__outputs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_workflows_get"];
        put?: never;
        /** Create Workflow */
        post: operations["create_workflow_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["get_workflow_workflows__workflow_id__get"];
        /** Update Workflow */
        put: operations["update_workflow_workflows__workflow_id__put"];
        post?: never;
        /** Delete Workflow */
        delete: operations["delete_workflow_workflows__workflow_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Workflow
         * @description Enqueue a run and return immediately with 202 — the run has not finished (NFR-01).
         */
        post: operations["run_workflow_workflows__workflow_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_workflows__workflow_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Workflow */
        post: operations["validate_workflow_workflows__workflow_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentFamily
         * @enum {string}
         */
        AgentFamily: "create" | "distribute";
        /**
         * AgentInput
         * @description One thing an agent needs to run, and where it may come from.
         */
        AgentInput: {
            /**
             * Accepts
             * @description Output names an earlier step may supply this under, in the order the agent prefers them
             */
            accepts: string[];
            /** Name */
            name: string;
            /**
             * Required
             * @description The step cannot run without it
             */
            required: boolean;
            /**
             * Settable
             * @description The user can type it in the step's settings; otherwise only an earlier step can supply it
             */
            settable: boolean;
        };
        /** AgentManifest */
        AgentManifest: {
            /**
             * Config Schema
             * @description JSON Schema of the configuration form. Filled from the agent's config model at runtime.
             */
            config_schema?: {
                [key: string]: unknown;
            } | null;
            /** Description */
            description: string;
            /** @default create */
            family: components["schemas"]["AgentFamily"];
            /**
             * Icon
             * @description Lucide icon name, e.g. 'telescope'
             */
            icon?: string | null;
            /**
             * Input Type
             * @description Model name in contracts.agent_io
             */
            input_type: string;
            /**
             * Inputs
             * @description What the agent needs. Filled from its input model at runtime.
             */
            inputs?: components["schemas"]["AgentInput"][];
            /**
             * Name
             * @description Unique agent_type
             */
            name: string;
            /**
             * Output Type
             * @description Model name in contracts.agent_io
             */
            output_type: string;
            /**
             * Outputs
             * @description What the agent hands on. Filled from its output model at runtime.
             */
            outputs?: components["schemas"]["AgentOutput"][];
            /**
             * Requires Approval
             * @description True for agents that send content out of the platform
             * @default false
             */
            requires_approval: boolean;
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /**
         * AgentOutput
         * @description One thing an agent hands on to the steps after it.
         */
        AgentOutput: {
            /** Name */
            name: string;
            /**
             * Title
             * @description What a person calls it, e.g. 'article'
             */
            title: string;
        };
        /**
         * ApprovalDecision
         * @enum {string}
         */
        ApprovalDecision: "approve" | "reject";
        /**
         * ApprovalInfo
         * @description The recorded human decision for a node that required approval (UC-04 audit trail).
         */
        ApprovalInfo: {
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Decided By Email */
            decided_by_email?: string | null;
            decision: components["schemas"]["ApprovalDecision"];
            /** Note */
            note?: string | null;
        };
        /**
         * ApprovalRecord
         * @description One decision in a run's audit trail — GET /runs/{run_id}/approvals (UC-04, S-06).
         */
        ApprovalRecord: {
            /** Agent Type */
            agent_type: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Decided By Email */
            decided_by_email?: string | null;
            decision: components["schemas"]["ApprovalDecision"];
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Note */
            note?: string | null;
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            decision: components["schemas"]["ApprovalDecision"];
            /** Note */
            note?: string | null;
        };
        /**
         * ConnectStart
         * @description Send the browser (or a popup) here. Valid for 10 minutes, in the browser that asked.
         */
        ConnectStart: {
            /** Authorization Url */
            authorization_url: string;
        };
        /**
         * Connection
         * @description A connected account on S-09 and in the credential picker (D-09). Never carries a token.
         *
         *     `status`: `expired` once Google has refused the connection or `expires_at` has passed;
         *     `expiring` within 7 days of `expires_at`; otherwise `connected`. `expires_at` is empty when
         *     Google gave no end date. `scopes` are the granted services as a person reads them
         *     ("YouTube", "Drive", "Gmail"). `used_by` counts this user's workflows whose steps reference it.
         */
        Connection: {
            /** Account Email */
            account_email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Provider
             * @constant
             */
            provider: "google";
            /** Scopes */
            scopes: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "connected" | "expiring" | "expired";
            /** Used By */
            used_by: number;
        };
        /** DevLoginRequest */
        DevLoginRequest: {
            /** Email */
            email: string;
        };
        /** GoogleConnect */
        GoogleConnect: {
            /** Authorization Url */
            authorization_url: string;
        };
        /** GoogleConnectRequest */
        GoogleConnectRequest: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "youtube" | "drive";
        };
        /** GoogleConnectionStatus */
        GoogleConnectionStatus: {
            /** Drive Connected */
            drive_connected: boolean;
            /** Youtube Connected */
            youtube_connected: boolean;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /**
             * Source
             * Format: uuid
             */
            source: string;
            /**
             * Target
             * Format: uuid
             */
            target: string;
        };
        /**
         * GraphNode
         * @description One agent on the canvas. `id` is generated by the frontend (crypto.randomUUID()).
         */
        GraphNode: {
            /** Agent Type */
            agent_type: string;
            /** Configuration */
            configuration?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            position?: components["schemas"]["Position"];
            /**
             * Requires Approval
             * @default false
             */
            requires_approval: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogEntry */
        LogEntry: {
            /** Agent Type */
            agent_type: string;
            approval?: components["schemas"]["ApprovalInfo"] | null;
            /** Completed At */
            completed_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["NodeStatus"];
        };
        /** Me */
        Me: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** NodeState */
        NodeState: {
            /** Agent Type */
            agent_type: string;
            approval?: components["schemas"]["ApprovalInfo"] | null;
            /** Completed At */
            completed_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["NodeStatus"];
        };
        /**
         * NodeStatus
         * @enum {string}
         */
        NodeStatus: "pending" | "running" | "retrying" | "awaiting_approval" | "success" | "failed" | "skipped";
        /**
         * OutputLink
         * @description How to get at one output: a URL for a file, the words themselves for text.
         */
        OutputLink: {
            /**
             * Expires In
             * @default 0
             */
            expires_in: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text?: string | null;
            /** Url */
            url?: string | null;
        };
        /** Position */
        Position: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
        };
        /** RunCreated */
        RunCreated: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * RunOutput
         * @description One thing a run produced.
         *
         *     `id` is what GET /outputs/{id} resolves: a download URL for a file, the content itself for
         *     text. `filename`, `mime_type` and `bytes` are a file's; text and links carry none of them.
         */
        RunOutput: {
            /** Agent Type */
            agent_type: string;
            /** Bytes */
            bytes?: number | null;
            /** Content Json */
            content_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "file" | "url";
            /** Mime Type */
            mime_type?: string | null;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
        };
        /** RunState */
        RunState: {
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Failed Nodes
             * @default 0
             */
            failed_nodes: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nodes */
            nodes?: components["schemas"]["NodeState"][];
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
            /**
             * Total Nodes
             * @default 0
             */
            total_nodes: number;
            /**
             * Workflow Id
             * Format: uuid
             */
            workflow_id: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "awaiting_approval" | "succeeded" | "failed" | "cancelled";
        /** RunSummary */
        RunSummary: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: "rejected" | null;
            status: components["schemas"]["RunStatus"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Edge Id */
            edge_id?: string | null;
            /** Message */
            message: string;
            /** Node Id */
            node_id?: string | null;
            /**
             * Severity
             * @default error
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        /** ValidationResult */
        ValidationResult: {
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Valid */
            valid: boolean;
        };
        /** WorkflowCreate */
        WorkflowCreate: {
            graph?: components["schemas"]["WorkflowGraph"];
            /**
             * Name
             * @default Untitled workflow
             */
            name: string;
        };
        /**
         * WorkflowGraph
         * @description What the canvas saves into `workflows.graph_definition`. Never holds secrets.
         */
        WorkflowGraph: {
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
        };
        /** WorkflowOut */
        WorkflowOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            graph: components["schemas"]["WorkflowGraph"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkflowSummary */
        WorkflowSummary: {
            /** Agent Types */
            agent_types: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            last_run?: components["schemas"]["RunSummary"] | null;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkflowUpdate */
        WorkflowUpdate: {
            graph?: components["schemas"]["WorkflowGraph"] | null;
            /** Name */
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_agents_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentManifest"][];
                };
            };
        };
    };
    dev_login_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_callback_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_connect_auth_google_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleConnect"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_status_auth_google_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleConnectionStatus"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    list_connections_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"][];
                };
            };
        };
    };
    start_google_connections_google_start_post: {
        parameters: {
            query?: {
                /** @description `popup`: the callback answers with a page that tells the opener and closes. */
                mode?: "redirect" | "popup";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectStart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Google connections aren't configured on this server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disconnect_connections__credential_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    download_outputs__output_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                output_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_approvals_runs__run_id__approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_runs__run_id__logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_runs__run_id__nodes__node_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_outputs_runs__run_id__outputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOutput"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSummary"][];
                };
            };
        };
    };
    create_workflow_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workflow_workflows__workflow_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workflow_workflows__workflow_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_workflow_workflows__workflow_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description The workflow has validation errors */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Job queue unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_runs_workflows__workflow_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_workflow_workflows__workflow_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
